# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

# TODO: Enter your application id below. If you have signed up
# using cloud.google.com/console use the "project id" for your application
# id.
application: operating-bolt-547
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /js
  static_dir: static/js

- url: /meta
  static_dir: static/meta

- url: /style
  static_dir: static/style

- url: /  
  script: main.app
- url: /index.html
  script: main.app

libraries:
- name: jinja2
  version: 2.6
  
inbound_services:
- warmup